name: Build Docker containers

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: contrib/docker/Dockerfile
          # platforms: linux/amd64,linux/386,linux/arm/v7,linux/arm64,linux/ppc64le
          platforms: linux/amd64
          push: true
          tags: ghcr.io/purplei2p/i2pd:latest
