name: Build Docker containers

on: push

jobs:
  docker:
    name: For ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: ['linux/amd64', 'linux/386', 'linux/arm64', 'linux/arm/v7']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./contrib/docker
          file: ./contrib/docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/purplei2p/i2pd:latest
